services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: expense_tracker
      POSTGRES_PASSWORD: "KcR6zVlwHUsVjMpAz8V9jw7xN_QKSb8E"
    volumes:
      - expense_tracker_data:/var/lib/postgresql/data
    profiles:
      - '' # Default profile
      - dev
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "bX0DgbFIRBz1uQZlPvSz2UQP-xl3pyHH"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - '' # Default profile
      - dev

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - '9090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: expense_tracker_test
      POSTGRES_PASSWORD: "7vwOyKM5_9UM19dyxiDvxvLSY7h09VJi"
    volumes:
      - expense_tracker_test_data:/var/lib/postgresql/data
    profiles:
      - '' # Default profile
      - test
  redis_test:
    image: redis:6.2.6
    ports:
      - '9091:6379'
    command: redis-server --requirepass "B4QSISN8Kd51iFZp6QD9SsZerQQrjUth"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - '' # Default profile
      - test

volumes:
  expense_tracker_data:
  expense_tracker_test_data:
